//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectEmp
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDetail
    {
        public int EmpId { get; set; }
        public string Name { get; set; }
        public string Degisnation { get; set; }
        public string Department { get; set; }
        public int ManagerId { get; set; }
        public int Salary { get; set; }
    }
}
